<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.AspNetCore.Authorization">
      <HintPath>..\..\..\..\.nuget\packages\microsoft.aspnetcore.app.ref\8.0.24\ref\net8.0\Microsoft.AspNetCore.Authorization.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Components">
      <HintPath>..\..\..\..\.nuget\packages\microsoft.aspnetcore.app.ref\8.0.24\ref\net8.0\Microsoft.AspNetCore.Components.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Mvc.Core">
      <HintPath>..\..\..\..\.nuget\packages\microsoft.aspnetcore.app.ref\8.0.24\ref\net8.0\Microsoft.AspNetCore.Mvc.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules.Identities.Core\Modules.Identities.Core.csproj" />
    <ProjectReference Include="..\Modules.Identities.Infrastructure\Modules.Identities.Infrastructure.csproj" />
    <ProjectReference Include="..\Shared.Infrastructure\Shared.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.10" />
  </ItemGroup>

</Project>
